### ISSUE TITLE
Pas de sauvegarde de la Commande Notifications

### ISSUE THREAD

**Issue by smuteau** [lunarok/jeedom_stock#5]
Lorsque que l'on choisit une commande pour la notification dans les paramètres, la sauvegarde ne garde pas la commande choisie -> on retrouve visuellement un blanc à la place.

{"createtime":"2016-11-08 22:55:20","commentaire":"","maximum":"","week":"2","alert":**["#1147#",""]**,"notifDaily":"2","notifWeekly":"5","notifStock":"20","updatetime":"2016-11-09 19:27:16","notifMonthly":"20"}

**Comment by smuteau** [comment]
Sous macOS, même comportement avec Firefox, Safari et Chrome.

**Comment by lunarok** [comment]
commit 00d7d461059489fa59e15552dcd09682f4661bc7
